# Generated by Django 5.2.5 on 2025-08-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='game',
            field=models.CharField(choices=[('NLHE', 'NLHE'), ('PLO', 'PLO'), ('PLO5', 'PLO5'), ('PLO8', 'PLO8'), ('MIXED', 'Mixed')], default='NLHE', max_length=5),
        ),
        migrations.AddField(
            model_name='tournament',
            name='seat_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='speed',
            field=models.CharField(choices=[('regular', 'Regular'), ('turbo', 'Turbo'), ('hyper', 'Hyper'), ('deepstack', 'Deepstack')], default='regular', max_length=10),
        ),
        migrations.AddField(
            model_name='tournament',
            name='table_size',
            field=models.CharField(choices=[('full', 'Full Ring'), ('8max', '8-max'), ('6max', '6-max'), ('hu', 'Heads-up')], default='8max', max_length=5),
        ),
        migrations.AddField(
            model_name='tournament',
            name='target_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='tournament',
            name='type',
            field=models.CharField(choices=[('MTT', 'MTT'), ('SAT', 'Satellite')], default='MTT', max_length=3),
        ),
    ]
