# Generated by Django 5.2.5 on 2025-08-13 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_bounties_won'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-start_time']},
        ),
    ]
